### ISSUE TITLE
docker-drawio: Drag and drop import of .vsdx files

### ISSUE THREAD

**Issue by Tobnord** [jgraph/docker-drawio#200]
I was wondering if it was intended that drag and drop importing of .vsdx files is supposed to be possible for the self-hosted docker version. It works exceptionally well when using [https://app.diagrams.net/](https://app.diagrams.net/). It also works when embedding the editor using [https://embed.diagrams.net/](https://embed.diagrams.net/) as host.

My issue is when hosting draw.io using docker. All features I have used have worked as intended, except for dropping a .vsdx file from the file explorer into the editor window.

This is the result of dropping the file:

<img width="508" height="260" alt="Image" src="https://github.com/user-attachments/assets/67446986-8bba-4d1a-8da6-b8916363bc0c" />

<img width="508" height="258" alt="Image" src="https://github.com/user-attachments/assets/e96bb920-7274-48bd-83dc-b7bf9d8d5d8d" />

Im guessing this has something to do with how the js scripts are loaded. Using app.diagrams.net the script "extensions.min.js" gets loaded when the editor opens. It gets loaded by bootstrap.js. However, there is a difference in the network tab when using the docker version.

"extensions.min.js" gets loaded when the docker version of the editor is first initialized, but it seems like "bootstrap.js" tries to load "extensions.min.js" again when i drop a .vsdx file into the editor. It seems like this might be the cause of the exception.

<img width="1247" height="539" alt="Image" src="https://github.com/user-attachments/assets/e6bb2001-2694-429c-a2c1-c630a4471ded" />
extensions.min.js:3851 Uncaught Class 'OrgChart.Annotations.CanBeNullAttribute' is already defined
set @ extensions.min.js:3851
define @ extensions.min.js:3851
(anonymous) @ extensions.min.js:3853
Bridge.assembly @ extensions.min.js:3851
(anonymous) @ extensions.min.js:3853

I have managed to reproduce this problem in all versions of docker-drawio from the tag 28.0.7 to latest. I'm hoping that this will be fixed soon, as this feature is just awesome!

**Comment by Tobnord** [comment]
It seems that this issue is not limited to drag and drop import of .vsdx files, but also when importing from the file -> import from -> device menu as well

**Comment by YaninaLeanIX** [comment]
Hey Team,
Are there any plans to fix it?

**Comment by davidjgraph** [comment]
It is fixed internally, there just hasn't been source code push for a while. Should be one before the end of the year.

**Comment by aselsing** [comment]
This issue still exists on the latest version. jgraph/drawio:29.3.2
I tested on the drawio website and its working there, but its on 29.3.4

**Comment by davidjgraph** [comment]
and with 29.3.5?

**Comment by aselsing** [comment]
I'll pull it and check before the weekend. Thank you for the quick tag push

**Comment by aselsing** [comment]
Deployed drawio:29.3.5, and it works! Thank you :) 

Note to anyone redeploying to the new tag: delete cookies and hard refresh the webpage, otherwise(for me atleast) the UI wont properly load.
